window.esdocSearchIndex = [
  [
    "vulp/src/context.js~context",
    "class/src/Context.js~Context.html",
    "<span>Context</span> <span class=\"search-result-import-path\">vulp/src/Context.js</span>",
    "class"
  ],
  [
    "vulp/src/jsonpointer/index.js~jsonpointer",
    "class/src/JSONPointer/index.js~JSONPointer.html",
    "<span>JSONPointer</span> <span class=\"search-result-import-path\">vulp/src/JSONPointer/index.js</span>",
    "class"
  ],
  [
    "vulp/src/transform.js~transform",
    "class/src/Transform.js~Transform.html",
    "<span>Transform</span> <span class=\"search-result-import-path\">vulp/src/Transform.js</span>",
    "class"
  ],
  [
    "vulp/src/state/index.js~box",
    "function/index.html#static-function-box",
    "<span>box</span> <span class=\"search-result-import-path\">vulp/src/state/index.js</span>",
    "function"
  ],
  [
    "vulp/src/utils/checktype.js~check",
    "variable/index.html#static-variable-check",
    "<span>check</span> <span class=\"search-result-import-path\">vulp/src/utils/checkType.js</span>",
    "variable"
  ],
  [
    "vulp/src/decorators/checkcontexttype.js~checkcontexttype",
    "function/index.html#static-function-checkContextType",
    "<span>checkContextType</span> <span class=\"search-result-import-path\">vulp/src/decorators/checkContextType.js</span>",
    "function"
  ],
  [
    "vulp/src/utils/choke.js~choke",
    "function/index.html#static-function-choke",
    "<span>choke</span> <span class=\"search-result-import-path\">vulp/src/utils/choke.js</span>",
    "function"
  ],
  [
    "vulp/src/scopes/combiner.js~combiner",
    "function/index.html#static-function-combiner",
    "<span>combiner</span> <span class=\"search-result-import-path\">vulp/src/scopes/combiner.js</span>",
    "function"
  ],
  [
    "vulp/src/decorators/component.js~component",
    "function/index.html#static-function-component",
    "<span>component</span> <span class=\"search-result-import-path\">vulp/src/decorators/component.js</span>",
    "function"
  ],
  [
    "vulp/src/decorators/controller.js~controller",
    "function/index.html#static-function-controller",
    "<span>controller</span> <span class=\"search-result-import-path\">vulp/src/decorators/controller.js</span>",
    "function"
  ],
  [
    "vulp/src/utils/curry.js~curry",
    "function/index.html#static-function-curry",
    "<span>curry</span> <span class=\"search-result-import-path\">vulp/src/utils/curry.js</span>",
    "function"
  ],
  [
    "vulp/src/utils/cycle.js~cycle",
    "function/index.html#static-function-cycle",
    "<span>cycle</span> <span class=\"search-result-import-path\">vulp/src/utils/cycle.js</span>",
    "function"
  ],
  [
    "vulp/src/decorators/dispatchchangesets.js~dispatchchangesets",
    "function/index.html#static-function-dispatchChangeSets",
    "<span>dispatchChangeSets</span> <span class=\"search-result-import-path\">vulp/src/decorators/dispatchChangeSets.js</span>",
    "function"
  ],
  [
    "vulp/src/views/dom.js~dom",
    "function/index.html#static-function-dom",
    "<span>dom</span> <span class=\"search-result-import-path\">vulp/src/views/dom.js</span>",
    "function"
  ],
  [
    "vulp/src/scopes/fragment.js~fragment",
    "function/index.html#static-function-fragment",
    "<span>fragment</span> <span class=\"search-result-import-path\">vulp/src/scopes/fragment.js</span>",
    "function"
  ],
  [
    "vulp/src/state/index.js~get",
    "function/index.html#static-function-get",
    "<span>get</span> <span class=\"search-result-import-path\">vulp/src/state/index.js</span>",
    "function"
  ],
  [
    "vulp/src/utils/patch.js~handler",
    "function/index.html#static-function-handler",
    "<span>handler</span> <span class=\"search-result-import-path\">vulp/src/utils/patch.js</span>",
    "function"
  ],
  [
    "vulp/src/state/index.js~is",
    "variable/index.html#static-variable-is",
    "<span>is</span> <span class=\"search-result-import-path\">vulp/src/state/index.js</span>",
    "variable"
  ],
  [
    "vulp/src/decorators/utils.js~ishandler",
    "variable/index.html#static-variable-isHandler",
    "<span>isHandler</span> <span class=\"search-result-import-path\">vulp/src/decorators/utils.js</span>",
    "variable"
  ],
  [
    "vulp/src/decorators/log.js~log",
    "function/index.html#static-function-log",
    "<span>log</span> <span class=\"search-result-import-path\">vulp/src/decorators/log.js</span>",
    "function"
  ],
  [
    "vulp/src/decorators/utils.js~mapattributes",
    "function/index.html#static-function-mapAttributes",
    "<span>mapAttributes</span> <span class=\"search-result-import-path\">vulp/src/decorators/utils.js</span>",
    "function"
  ],
  [
    "vulp/src/decorators/memoize.js~memoize",
    "function/index.html#static-function-memoize",
    "<span>memoize</span> <span class=\"search-result-import-path\">vulp/src/decorators/memoize.js</span>",
    "function"
  ],
  [
    "vulp/src/decorators/mount.js~mount",
    "function/index.html#static-function-mount",
    "<span>mount</span> <span class=\"search-result-import-path\">vulp/src/decorators/mount.js</span>",
    "function"
  ],
  [
    "vulp/src/decorators/name.js~name",
    "function/index.html#static-function-name",
    "<span>name</span> <span class=\"search-result-import-path\">vulp/src/decorators/name.js</span>",
    "function"
  ],
  [
    "vulp/src/decorators/utils.js~normalize",
    "function/index.html#static-function-normalize",
    "<span>normalize</span> <span class=\"search-result-import-path\">vulp/src/decorators/utils.js</span>",
    "function"
  ],
  [
    "vulp/src/decorators/utils.js~specdecorator",
    "function/index.html#static-function-specDecorator",
    "<span>specDecorator</span> <span class=\"search-result-import-path\">vulp/src/decorators/utils.js</span>",
    "function"
  ],
  [
    "vulp/src/decorators/styler.js~styler",
    "function/index.html#static-function-styler",
    "<span>styler</span> <span class=\"search-result-import-path\">vulp/src/decorators/styler.js</span>",
    "function"
  ],
  [
    "vulp/src/state/index.js~unbox",
    "function/index.html#static-function-unbox",
    "<span>unbox</span> <span class=\"search-result-import-path\">vulp/src/state/index.js</span>",
    "function"
  ],
  [
    "vulp/src/scopes/value.js~value",
    "function/index.html#static-function-value",
    "<span>value</span> <span class=\"search-result-import-path\">vulp/src/scopes/value.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/context.js",
    "file/src/Context.js.html",
    "src/Context.js",
    "file"
  ],
  [
    "src/context.js~context#changed",
    "class/src/Context.js~Context.html#instance-method-changed",
    "src/Context.js~Context#changed",
    "method"
  ],
  [
    "src/context.js~context#constructor",
    "class/src/Context.js~Context.html#instance-constructor-constructor",
    "src/Context.js~Context#constructor",
    "method"
  ],
  [
    "src/context.js~context#get",
    "class/src/Context.js~Context.html#instance-method-get",
    "src/Context.js~Context#get",
    "method"
  ],
  [
    "src/context.js~context#update",
    "class/src/Context.js~Context.html#instance-method-update",
    "src/Context.js~Context#update",
    "method"
  ],
  [
    "src/context.js~context.ofstate",
    "class/src/Context.js~Context.html#static-method-ofState",
    "src/Context.js~Context.ofState",
    "method"
  ],
  [
    "src/jsonpointer/index.js",
    "file/src/JSONPointer/index.js.html",
    "src/JSONPointer/index.js",
    "file"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer#concat",
    "class/src/JSONPointer/index.js~JSONPointer.html#instance-method-concat",
    "src/JSONPointer/index.js~JSONPointer#concat",
    "method"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer#constructor",
    "class/src/JSONPointer/index.js~JSONPointer.html#instance-constructor-constructor",
    "src/JSONPointer/index.js~JSONPointer#constructor",
    "method"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer#first",
    "class/src/JSONPointer/index.js~JSONPointer.html#instance-method-first",
    "src/JSONPointer/index.js~JSONPointer#first",
    "method"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer#last",
    "class/src/JSONPointer/index.js~JSONPointer.html#instance-method-last",
    "src/JSONPointer/index.js~JSONPointer#last",
    "method"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer#size",
    "class/src/JSONPointer/index.js~JSONPointer.html#instance-method-size",
    "src/JSONPointer/index.js~JSONPointer#size",
    "method"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer#slice",
    "class/src/JSONPointer/index.js~JSONPointer.html#instance-method-slice",
    "src/JSONPointer/index.js~JSONPointer#slice",
    "method"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer#toimmutable",
    "class/src/JSONPointer/index.js~JSONPointer.html#instance-method-toImmutable",
    "src/JSONPointer/index.js~JSONPointer#toImmutable",
    "method"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer#torfc",
    "class/src/JSONPointer/index.js~JSONPointer.html#instance-method-toRFC",
    "src/JSONPointer/index.js~JSONPointer#toRFC",
    "method"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer#tokens",
    "class/src/JSONPointer/index.js~JSONPointer.html#instance-member-tokens",
    "src/JSONPointer/index.js~JSONPointer#tokens",
    "member"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer.ofstring",
    "class/src/JSONPointer/index.js~JSONPointer.html#static-method-ofString",
    "src/JSONPointer/index.js~JSONPointer.ofString",
    "method"
  ],
  [
    "src/jsonpointer/index.js~jsonpointer.oftokens",
    "class/src/JSONPointer/index.js~JSONPointer.html#static-method-ofTokens",
    "src/JSONPointer/index.js~JSONPointer.ofTokens",
    "method"
  ],
  [
    "src/jsonpointer/index.js~tokenlist",
    "typedef/index.html#static-typedef-TokenList",
    "src/JSONPointer/index.js~TokenList",
    "typedef"
  ],
  [
    "src/patch.js",
    "file/src/Patch.js.html",
    "src/Patch.js",
    "file"
  ],
  [
    "src/patch.js~patch",
    "typedef/index.html#static-typedef-Patch",
    "src/Patch.js~Patch",
    "typedef"
  ],
  [
    "src/transform.js",
    "file/src/Transform.js.html",
    "src/Transform.js",
    "file"
  ],
  [
    "src/transform.js~map",
    "typedef/index.html#static-typedef-Map",
    "src/Transform.js~Map",
    "typedef"
  ],
  [
    "src/transform.js~transform#apply",
    "class/src/Transform.js~Transform.html#instance-method-apply",
    "src/Transform.js~Transform#apply",
    "method"
  ],
  [
    "src/transform.js~transform#constructor",
    "class/src/Transform.js~Transform.html#instance-constructor-constructor",
    "src/Transform.js~Transform#constructor",
    "method"
  ],
  [
    "src/transform.js~transform#equals",
    "class/src/Transform.js~Transform.html#instance-method-equals",
    "src/Transform.js~Transform#equals",
    "method"
  ],
  [
    "src/transform.js~transform#isidentity",
    "class/src/Transform.js~Transform.html#instance-method-isIdentity",
    "src/Transform.js~Transform#isIdentity",
    "method"
  ],
  [
    "src/transform.js~transform#length",
    "class/src/Transform.js~Transform.html#instance-member-length",
    "src/Transform.js~Transform#length",
    "member"
  ],
  [
    "src/transform.js~transform#map",
    "class/src/Transform.js~Transform.html#instance-member-map",
    "src/Transform.js~Transform#map",
    "member"
  ],
  [
    "src/transform.js~transform#sub",
    "class/src/Transform.js~Transform.html#instance-method-sub",
    "src/Transform.js~Transform#sub",
    "method"
  ],
  [
    "src/transform.js~transform#totargets",
    "class/src/Transform.js~Transform.html#instance-method-toTargets",
    "src/Transform.js~Transform#toTargets",
    "method"
  ],
  [
    "src/transform.js~transform.oftargets",
    "class/src/Transform.js~Transform.html#static-method-ofTargets",
    "src/Transform.js~Transform.ofTargets",
    "method"
  ],
  [
    "src/decorators/checkcontexttype.js",
    "file/src/decorators/checkContextType.js.html",
    "src/decorators/checkContextType.js",
    "file"
  ],
  [
    "src/decorators/component.js",
    "file/src/decorators/component.js.html",
    "src/decorators/component.js",
    "file"
  ],
  [
    "src/decorators/controller.js",
    "file/src/decorators/controller.js.html",
    "src/decorators/controller.js",
    "file"
  ],
  [
    "src/decorators/debug.js",
    "file/src/decorators/debug.js.html",
    "src/decorators/debug.js",
    "file"
  ],
  [
    "src/decorators/dispatchchangesets.js",
    "file/src/decorators/dispatchChangeSets.js.html",
    "src/decorators/dispatchChangeSets.js",
    "file"
  ],
  [
    "src/decorators/index.js",
    "file/src/decorators/index.js.html",
    "src/decorators/index.js",
    "file"
  ],
  [
    "src/decorators/index.js~hoc",
    "typedef/index.html#static-typedef-HOC",
    "src/decorators/index.js~HOC",
    "typedef"
  ],
  [
    "src/decorators/log.js",
    "file/src/decorators/log.js.html",
    "src/decorators/log.js",
    "file"
  ],
  [
    "src/decorators/memoize.js",
    "file/src/decorators/memoize.js.html",
    "src/decorators/memoize.js",
    "file"
  ],
  [
    "src/decorators/mount.js",
    "file/src/decorators/mount.js.html",
    "src/decorators/mount.js",
    "file"
  ],
  [
    "src/decorators/name.js",
    "file/src/decorators/name.js.html",
    "src/decorators/name.js",
    "file"
  ],
  [
    "src/decorators/styler.js",
    "file/src/decorators/styler.js.html",
    "src/decorators/styler.js",
    "file"
  ],
  [
    "src/decorators/utils.js",
    "file/src/decorators/utils.js.html",
    "src/decorators/utils.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~element",
    "typedef/index.html#static-typedef-element",
    "src/index.js~element",
    "typedef"
  ],
  [
    "src/scopes/combiner.js",
    "file/src/scopes/combiner.js.html",
    "src/scopes/combiner.js",
    "file"
  ],
  [
    "src/scopes/fragment.js",
    "file/src/scopes/fragment.js.html",
    "src/scopes/fragment.js",
    "file"
  ],
  [
    "src/scopes/index.js",
    "file/src/scopes/index.js.html",
    "src/scopes/index.js",
    "file"
  ],
  [
    "src/scopes/index.js~boundscopefactory",
    "typedef/index.html#static-typedef-BoundScopeFactory",
    "src/scopes/index.js~BoundScopeFactory",
    "typedef"
  ],
  [
    "src/scopes/index.js~scope",
    "typedef/index.html#static-typedef-Scope",
    "src/scopes/index.js~Scope",
    "typedef"
  ],
  [
    "src/scopes/index.js~scopefactory",
    "typedef/index.html#static-typedef-ScopeFactory",
    "src/scopes/index.js~ScopeFactory",
    "typedef"
  ],
  [
    "src/scopes/value.js",
    "file/src/scopes/value.js.html",
    "src/scopes/value.js",
    "file"
  ],
  [
    "src/state/index.js",
    "file/src/state/index.js.html",
    "src/state/index.js",
    "file"
  ],
  [
    "src/tests/context.js",
    "file/src/tests/Context.js.html",
    "src/tests/Context.js",
    "file"
  ],
  [
    "src/tests/transform.js",
    "file/src/tests/Transform.js.html",
    "src/tests/Transform.js",
    "file"
  ],
  [
    "src/tests/state.js",
    "file/src/tests/state.js.html",
    "src/tests/state.js",
    "file"
  ],
  [
    "src/utils/checktype.js",
    "file/src/utils/checkType.js.html",
    "src/utils/checkType.js",
    "file"
  ],
  [
    "src/utils/checktype.js~type",
    "external/index.html",
    "src/utils/checkType.js~Type",
    "external"
  ],
  [
    "src/utils/choke.js",
    "file/src/utils/choke.js.html",
    "src/utils/choke.js",
    "file"
  ],
  [
    "src/utils/curry.js",
    "file/src/utils/curry.js.html",
    "src/utils/curry.js",
    "file"
  ],
  [
    "src/utils/cycle.js",
    "file/src/utils/cycle.js.html",
    "src/utils/cycle.js",
    "file"
  ],
  [
    "src/utils/patch.js",
    "file/src/utils/patch.js.html",
    "src/utils/patch.js",
    "file"
  ],
  [
    "src/views/dom.js",
    "file/src/views/dom.js.html",
    "src/views/dom.js",
    "file"
  ],
  [
    "src/views/index.js",
    "file/src/views/index.js.html",
    "src/views/index.js",
    "file"
  ],
  [
    "src/views/index.js~boundviewfactory",
    "typedef/index.html#static-typedef-BoundViewFactory",
    "src/views/index.js~BoundViewFactory",
    "typedef"
  ],
  [
    "src/views/index.js~view",
    "typedef/index.html#static-typedef-View",
    "src/views/index.js~View",
    "typedef"
  ],
  [
    "src/views/index.js~viewfactory",
    "typedef/index.html#static-typedef-ViewFactory",
    "src/views/index.js~ViewFactory",
    "typedef"
  ]
]